General improvements to documentation
bloomberg/pytest-memray pull request #26
Opened 2022-05-17 23:12 UTC by gaborbernat

Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>

2022-05-18 13:32 UTC, pablogsal commented on README.md
> +[as shown here](https://pytest-memray.readthedocs.io/en/latest/usage.html#allocation-tracking):
Please, leave the inlined outputs. I prefer to have this in the readme as is, even if we need to manually synchronize it

2022-05-18 13:35 UTC, pablogsal requested changes

2022-05-18 13:35 UTC, pablogsal commented on README.md
> -## Configuration
The same for this, I prefer to have this in the readme. We are not going to change this a lot anyway so it has low maintenance

2022-05-18 13:36 UTC, gaborbernat commented on README.md
> +[as shown here](https://pytest-memray.readthedocs.io/en/latest/usage.html#allocation-tracking):
My only complaint is that gets quickly out of date 🤔

2022-05-18 13:37 UTC, gaborbernat commented on README.md
> -## Configuration
We already missed this update within https://github.com/bloomberg/pytest-memray/pull/14 ...

2022-05-20 13:57 UTC, pablogsal approved these changes

2022-05-20 13:58 UTC, merged