Ensure tests marked by memray run even if `--memray` is not passed
bloomberg/pytest-memray pull request #57
Opened 2022-11-30 13:37 UTC by pablogsal

The fact that the plugin is not registered if `--memray` is not
provided has proven to be a source of confusion and provides a bad
UX.

*Issue number of the reported bug or feature request: #<number>*

**Describe your changes**
A clear and concise description of the changes you have made.

**Testing performed**
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.

**Additional context**
Add any other context about your contribution here.

2022-11-30 15:12 UTC, gaborbernat reviewed
Is the CI failing? Also, let's add a changelog entry.

2022-11-30 16:27 UTC, pablogsal commented
> The CI is failing?

We need to fix the flaky test. Is passing now

2022-11-30 17:27 UTC, gaborbernat requested changes
Needs a news entry here https://github.com/bloomberg/pytest-memray/tree/main/docs/news

2022-12-01 15:06 UTC, gaborbernat approved these changes

2022-12-01 15:06 UTC, merged