Allow to customize the tracebacks one error
bloomberg/pytest-memray pull request #58
Opened 2022-11-30 14:48 UTC by pablogsal

To allow users to get as much information as they need, add two new
options to the command line invocation that allows to:

* Customize how many stacks to show for every allocation.
* Obtain native traces and show the hybrid stack.

*Issue number of the reported bug or feature request: #<number>*

**Describe your changes**
A clear and concise description of the changes you have made.

**Testing performed**
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.

**Additional context**
Add any other context about your contribution here.

2022-11-30 15:12 UTC, gaborbernat requested changes
Can you resolve the merge conflicts, add changelog and fix the CI?

2022-11-30 16:32 UTC, pablogsal commented
> Can you resolve the merge conflicts, add changelog and fix the CI?

Done

2022-11-30 17:31 UTC, gaborbernat approved these changes

2022-11-30 17:31 UTC, gaborbernat commented on src/pytest_memray/utils.py
> +    ivalue = int(value)
ivalue is not part of a dictionary, can we instead use parsed or i_value?

2022-12-01 15:05 UTC, gaborbernat approved these changes

2022-12-01 15:06 UTC, merged